### ISSUE TITLE
getViewActivePanel может вернуть undefined во время обновления

### ISSUE THREAD

**Issue by eolme-fallback** [HappySanta/router#12]
Ломается VKUI, если агрессивно по view'хам прыгать.

Заменил у себя на:
```js
let activePanel;

if (location.route.getViewId() === viewId) {
  activePanel = location.route.getPanelId();
} else {
  activePanel = location.state.panelInView[viewId] ?? location.route.getPanelId();
}
```

**Comment by eolme-fallback** [comment]
Правда на iOS ломается анимация, но ничего лучше пока не придумал.

**Comment by stels-cs** [comment]
`undefined` может возвращаться для панелей на view которые еще ни разу не открывались, обычно это не доставляет проблем.

В каком случае у вас ломается VKUI?

**Comment by stels-cs** [comment]
Возможно проблемы были связаны с #11, проверьте на версии 0.1.5 есть ли такая проблема

**Comment by eolme-fallback** [comment]
Я бы сам тест написал, но без eslint - боль
