### ISSUE TITLE
Не работает последняя версия библиотеки

### ISSUE THREAD

**Issue by k-egor-smirnov** [HappySanta/router#23]
В последней версии библиотеки (0.1.15) код не собран, из-за чего энтрипоинт в папке dist отсутствует

Примеры:
[0.1.15](https://unpkg.com/@happysanta/router@0.1.15)
[0.1.14](https://unpkg.com/@happysanta/router@0.1.14)

**Comment by stels-cs** [comment]
fixed 0.1.16

**Comment by k-egor-smirnov** [comment]
Стало лучше, спасибо!
