### ISSUE TITLE
Затирание window.location.hash

### ISSUE THREAD

**Issue by Sozonov** [HappySanta/router#24]
После запуска роутер перезаписывает значение window.location.hash

Пример: имеем приложение, открытое с utm меткой
https://vk.com/app11111111#utm_source=vk&utm_campaign=blabla
Если не запускать роутер, то window.location.hash будет равен "#utm_source=vk&utm_campaign=blabla"
А если запустить, то будет равен "#/"

Как правильно работать с параметрами запуска?

**Comment by stels-cs** [comment]
Значение window.location.hash которое было до запуска роутера лежит тут
```ts
router.startHash
```

**Comment by Sozonov** [comment]
О супер! Спасибо!
