### ISSUE TITLE
Не обновляется контент при переходе на такую же страницу.

### ISSUE THREAD

**Issue by zn** [HappySanta/router#25]
Здравствуйте! В вашем примере [router-example](https://github.com/HappySanta/router-example) если на страницу продукта добавить ссылку на другой продукт, то контент не обновляется почему-то.

Поподробнее:
[Сюда](https://github.com/HappySanta/router-example/blob/5499475199cd4ea361c1ebf34f4ab1159c6047a7/src/panels/Product.js#L38) вставляю такой код:
```js
<Button mode="commerce" onClick={() => router.pushPage(PAGE_PRODUCT, { id: '2' })}>
	Product #2
</Button>
```
При клике на кнопку в логах пишется, что совершается переход на страницу PAGE_PRODUCT, но контент на странице не обновляется.
![image](https://user-images.githubusercontent.com/39989294/124946506-fd5ba780-e006-11eb-8270-85f41faf5b09.png)
Скажите, пожалуйста, как это пофиксить?

**Comment by stels-cs** [comment]
По гайдлайнам такого быть не должно, надо переходить на новую страницу

но если вы точно уверены что вам такое надо, то надо отказаться от хука `useParams`, вместо него можно использовать такой код
```js
const location = useLocation(true);
const params = location.getParams();
```

`useParams` намеренно кеширует параметры чтобы избежать лишних ререндеров во время анимаций смены панелей

**Comment by zn** [comment]
Да, так и сделал: юзаю location.getParams() и ручками обновляю стейты. Спасибо
