### ISSUE TITLE
Краш при закрытии модалки

### ISSUE THREAD

**Issue by sitenative** [HappySanta/router#26]
При закрытии модалки путем клика по кнопке с router.popPage() через раз происходит краш приложения.
При свайпе окна такого не происходит.
![image](https://user-images.githubusercontent.com/70588005/137781101-ee8b52cf-3e65-45e2-b5fe-ef487e073223.png)

**Comment by stels-cs** [comment]
- попрбуйте использовать **useThrottlingLocation** вместо useLocation для получения modalId

- воспроизводиться ли проблема если переходить по модалкам медленно?

**Comment by tadappnative** [comment]
Проблема наблюдалась только в среде node v14.17.5
После обновления до v16.13.0 не воспроизводится. Можно закрывать

**Comment by sitenative** [comment]
Проблема наблюдалась только в среде node v14.17.5
После обновления до v16.13.0 не воспроизводится. Можно закрывать
