### ISSUE TITLE
Расхождение версий в npm и github

### ISSUE THREAD

**Issue by Melodyn** [HappySanta/router#31]
Подтянулась из npm версия роутера 1.2.2: https://www.npmjs.com/package/@happysanta/router хотя на github последняя версия 0.3.0. Основная проблема в том, что версия 1.2.2 из npm имеет какие-то отличия и у меня уже приложение не собралось. Но в подробности я не вдавался, т.к. не нашёл никакого лога изменений и просто откатился на 0.1.21. 

Либо что-то где-то залагало, либо выпущена мажорная версия без описания, в общем, хотелось бы просто знать что произошло.

Лог ошибки при сборке:
```
ERROR in ./node_modules/@happysanta/router/dist/lib/workWithPathRegexp.js 11:33-55
Module not found: Error: Can't resolve 'querystring' in '/usr/src/app/frontend/node_modules/@happysanta/router/dist/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
        - install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "querystring": false }
 @ ./node_modules/@happysanta/router/dist/lib/entities/Route.js 10:26-58
 @ ./node_modules/@happysanta/router/dist/index.js 19:13-44
 @ ./src/App.jsx 24:0-51 275:92-114
 @ ./src/index.jsx 11:0-28 22:50-53
```

PS
querystring [уже легаси](https://nodejs.org/dist/latest-v16.x/docs/api/querystring.html#query-string), лучше использовать URLSearchParams

**Comment by Melodyn** [comment]
Заюзал версию 0.3.0 и получилось собрать приложение, если не обновлять зависимости, ошибка при сборке появляется после обновления то ли babel то ли webpack пока не разобрался.

**Comment by Melodyn** [comment]
Заслал ПР на легаси. Нумерацию свести с npm скорее всего, придётся повышением версии в гитхабе.

**Comment by stels-cs** [comment]
Спасибо за активность. С версиями действительно вышел косяк, версия 1.2.2 по ошибке была опубликована с тегом 
latest вместо beta.
Обновитесь до версии 0.3.1, проблема c querystring должна быть решена.

**Comment by Melodyn** [comment]
Всё отлично - версии совпадают, приложение собирается. Спасибо!
