### ISSUE TITLE
Плавающий баг с переходами по истории

### ISSUE THREAD

**Issue by eolme-fallback** [HappySanta/router#7]
Связано скорее всего с `pushPageAfterPreviews`.

**Comment by eolme-fallback** [comment]
Тестами бы покрыть переходы по истории.

**Comment by stels-cs** [comment]
А в чем проявляется баг?

**Comment by eolme-fallback** [comment]
На popstate переходит не туда, куда планировалось, возможно я не так использую метод.
```js
pushPageAfterPreviews(PAGE_MAIN, PAGE_MAP)
```
Если правильно понял, он должен откатить историю до `PAGE_MAIN` и пушнуть `PAGE_MAP`, но после последующих переходов иногда всплывают состояния между `PAGE_MAIN` и `PAGE_MAP`. Скорее всего offset не правильно считает.

**Comment by stels-cs** [comment]
PAGE_MAIN
...
...
... <тут какие-то страницы>
...
...
PAGE_MAP <- из этого состояния делается pushPageAfterPreviews(PAGE_MAIN, PAGE_MAP)?

**Comment by eolme-fallback** [comment]
Нет
