### ISSUE TITLE
Метод для перехода к конкретной Page в истории

### ISSUE THREAD

**Issue by eolme-fallback** [HappySanta/router#8]

**Comment by stels-cs** [comment]
А какой юзкейс этого метода?

- в общем случае страница может быть в истории несколько раз
- еще может быть страница /product/12 /product/13 /product/14. Формально это одна и та же страница но с разными параметрами, как в этом случае должно работать не очень понятно

Любой вариант можно реализовать если найти в `router.history.stack` нужную позицию, рассчитать расстояние относительно `router.history.currentIndex` и сделать `router.popPageTo на это расстояние`

Чтобы красивее сделать хочется понять юзкейс

**Comment by eolme-fallback** [comment]
Возможно тогда стоит добавить 2 метода: переход к странице с начала истории и с конца.
Смысл в том, чтобы как раз не хранить у себя в приложении offset куда нужно прыгнуть.

**Comment by stels-cs** [comment]
А что у вас за логика навигации где нужны такие сложные переходы на много шагов назад?

**Comment by eolme-fallback** [comment]
Ну допустим такой кейс:

У нас большая форма в несколько экранов, и после подтверждения пользователю предлагается вернуться на начало оформления, чтобы отправить ещё одну заявку (как раз этот прыжок), либо на какой-то другой экран (пуш).

(конечно можно сделать по-другому, взял более простой кейс  для наглядности)

**Comment by stels-cs** [comment]
Тоесть у вас будет

MAIN_PAGE
...
... какие-то еще страницы
...
PAGE_DONE <- и отсюда хочется прыжок в MAIN_PAGE?

**Comment by eolme-fallback** [comment]
MAIN_PAGE
...
... какие-то страницы
...
PAGE_ORDER_START
...
... еще какие-то страницы
...
PAGE_ORDER_DONE <- и отсюда хочется прыжок в ORDER_START

(если что это все условно)

**Comment by stels-cs** [comment]
в версии 0.1.3 расширен метод `popPageTo`, теперь туда можно передать id страницы и будет осуществлен переход до нее
```js
router.popPageTo(ORDER_START)
```
